[package]
name = "ezconf"
version = "0.1.0"
authors = ["Daniel Go√ü <developer@flashsystems.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
